services:
  - type: web
    name: ziadatravel
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      bash build.sh
    startCommand: |
      gunicorn tours_travels.wsgi:application \
        --bind 0.0.0.0:$PORT \
        --workers $WEB_CONCURRENCY \
        --timeout $GUNICORN_TIMEOUT
    healthCheckPath: /health/
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tours_travels.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ziadatravel.onrender.com,.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ziadatravel-db
          property: connectionString
      - key: EMAIL_PROVIDER
        value: smtp
      - key: DEFAULT_FROM_EMAIL
        value: Ziada Tours and Travel <info@ziadatoursandtravel.com>
      - key: ADMIN_EMAIL
        value: info@ziadatoursandtravel.com
      - key: EXTRA_EMAIL_RECIPIENTS
        value: ""
      - key: SITE_URL
        value: https://ziadatravel.onrender.com
      - key: EMAIL_HOST
        value: smtp-relay.brevo.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: MAILTRAP_API_TOKEN
        sync: false

  - type: redis
    name: ziadatravel-redis
    region: frankfurt
    plan: free

databases:
  - name: ziadatravel-db
    databaseName: ziadatravel
    user: ziadatravel_user
    region: frankfurt
    plan: free
    postgresMajorVersion: 15
